import fs from 'fs';
import path from 'path';

export async function generateBotScript(taskDescription: string, language: string = 'python'): Promise<string> {
    console.log(`[Tool: generate_bot_script] Writing output script for: ${taskDescription}`);
    
    // In actual implementation, the LLM itself would generate this code. 
    // This wrapper takes the LLM's generated script block and saves it to a file.
    
    const scriptPath = path.resolve(process.cwd(), `OPA_Automation_${Date.now()}.${language === 'python' ? 'py' : 'js'}`);
    
    let content = ``;
    if (language === 'python') {
        content = `#!/usr/bin/env python3
# Automated Bot Script generated by OPA
# Task: ${taskDescription}
# Generated: ${new Date().toISOString()}

import sys
import requests
import json
import time
from datetime import datetime

def main():
    print(f"[$(datetime.now())] Starting automated task: ${taskDescription}")
    
    # Example automation logic - customize based on your needs
    try:
        # Log start time
        start_time = time.time()
        
        # Placeholder for actual automation logic
        # This script can be customized to perform various tasks:
        # - API requests
        # - File operations
        # - Data processing
        # - Scheduled tasks
        
        print("[$(datetime.now())] Task completed successfully")
        print(f"Execution time: {time.time() - start_time:.2f} seconds")
        
    except Exception as e:
        print(f"[$(datetime.now())] Error during execution: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
`;
    } else {
        content = `// Automated Bot Script generated by OPA
// Task: ${taskDescription}
// Generated: ${new Date().toISOString()}

const axios = require('axios');

async function main() {
    const startTime = Date.now();
    console.log(\`[\${new Date().toISOString()}] Starting automated task: ${taskDescription}\`);
    
    try {
        // Example automation logic - customize based on your needs
        // This script can be customized to perform various tasks:
        // - API requests
        // - File operations
        // - Data processing
        // - Scheduled tasks
        
        console.log(\`[\${new Date().toISOString()}] Task completed successfully\`);
        console.log(\`Execution time: \${(Date.now() - startTime) / 1000}s\`);
        
    } catch (error) {
        console.error(\`[\${new Date().toISOString()}] Error during execution:\`, error.message);
        process.exit(1);
    }
}

main().catch(console.error);
`;
    }

    fs.writeFileSync(scriptPath, content, 'utf8');
    
    return `Bot automation script generated successfully at: ${scriptPath}`;
}
